export const FETCH_LIVE_EVENT_REQUEST = 'FETCH_LIVE_EVENT_REQUEST'
export const FETCH_LIVE_EVENT_SUCCESS = 'FETCH_LIVE_EVENT_SUCCESS'
export const FETCH_LIVE_EVENT_FAILURE = 'FETCH_LIVE_EVENT_FAILURE'

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE'

export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'
export const UPLOAD_INPUT_CHANGE = 'UPLOAD_INPUT_CHANGE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'