export const FETCH_LIVE_EVENT_REQUEST = 'FETCH_LIVE_EVENT_REQUEST'
export const FETCH_LIVE_EVENT_SUCCESS = 'FETCH_LIVE_EVENT_SUCCESS'
export const FETCH_LIVE_EVENT_FAILURE = 'FETCH_LIVE_EVENT_FAILURE'