export const FETCH_LIVE_EVENT_REQUEST = 'FETCH_LIVE_EVENT_REQUEST'
export const FETCH_LIVE_EVENT_SUCCESS = 'FETCH_LIVE_EVENT_SUCCESS'
export const FETCH_LIVE_EVENT_FAILURE = 'FETCH_LIVE_EVENT_FAILURE'

export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'
