export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const GET_LOTS_REQUEST = 'GET_LOTS_REQUEST'
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS'
export const GET_LOT_FAILURE = 'GET_LOT_FAILURE'