export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'
export const CREATE_LIVE_EVENT_REQUEST = 'CREATE_LIVE_EVENT_REQUEST'
export const CREATE_LIVE_EVENT_SUCCESS = 'CREATE_LIVE_EVENT_SUCCESS'
export const CREATE_LIVE_EVENT_FAILURE = 'CREATE_LIVE_EVENT_FAILURE'

export const FETCH_LIVE_EVENTS_REQUEST = 'FETCH_LIVE_EVENTS_REQUEST'
export const FETCH_LIVE_EVENTS_SUCCESS = 'FETCH_LIVE_EVENTS_SUCCESS'
export const FETCH_LIVE_EVENTS_FAILURE = 'FETCH_LIVE_EVENTS_FAILURE'

export const DELETE_LIVE_EVENT_REQUEST = 'DELETE_LIVE_EVENT_REQUEST'
export const DELETE_LIVE_EVENT_SUCCESS = 'DELETE_LIVE_EVENT_SUCCESS'
export const DELETE_LIVE_EVENT_FAILURE = 'DELETE_LIVE_EVENT_FAILURE'

export const EDIT_LIVE_EVENT_REQUEST = 'EDIT_LIVE_EVENT_REQUEST'
export const EDIT_LIVE_EVENT_SUCCESS = 'EDIT_LIVE_EVENT_SUCCESS'
export const EDIT_LIVE_EVENT_FAILURE = 'EDIT_LIVE_EVENT_FAILURE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'