export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'
export const CREATE_LIVE_EVENT_REQUEST = 'CREATE_LIVE_EVENT_REQUEST'
export const CREATE_LIVE_EVENT_SUCCESS = 'CREATE_LIVE_EVENT_SUCCESS'
export const CREATE_LIVE_EVENT_FAILURE = 'CREATE_LIVE_EVENT_FAILURE'