export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const GET_LOTS_REQUEST = 'GET_LOTS_REQUEST'
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS'
export const GET_LOTS_FAILURE = 'GET_LOTS_FAILURE'

export const GET_LOT_REQUEST = 'GET_LOT_REQUEST'
export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS'
export const GET_LOT_FAILURE = 'GET_LOT_FAILURE'

export const GET_PREOFFERS_REQUEST = 'GET_PREOFFERS_REQUEST'
export const GET_PREOFFERS_SUCCESS = 'GET_PREOFFERS_SUCCESS'
export const GET_PREOFFERS_FAILURE = 'GET_PREOFFERS_FAILURE'

export const GET_MY_PREOFFERS_REQUEST = 'GET_MY_PREOFFERS_REQUEST'
export const GET_MY_PREOFFERS_SUCCESS = 'GET_MY_PREOFFERS_SUCCESS'
export const GET_MY_PREOFFERS_FAILURE = 'GET_MY_PREOFFERS_FAILURE'

export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'

export const CREATE_PREOFFER_REQUEST = 'CREATE_PREOFFER_REQUEST'
export const CREATE_PREOFFER_SUCCESS = 'CREATE_PREOFFER_SUCCESS'
export const CREATE_PREOFFER_FAILURE = 'CREATE_PREOFFER_FAILURE'

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'
